services:
  db:
    build: ./db
    image: "arosa-db:latest"
    depends_on:
      - httpd
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db_run:/run/mysqld/
      - db_sql_dumps:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
  php56-fpm:
    build: ./php/5.6
    depends_on:
      - httpd
      - db
    image: "arosa-php:5.6-fpm"
    volumes:
      - php_run:/run/php/
      - db_run:/run/mysqld/
      - ./arosa/php/5.6/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - httpd_data:/var/www
  php70-fpm:
    build: ./php/7.0
    depends_on:
      - httpd
      - db
    image: "arosa-php:7.0-fpm"
    volumes:
      - php_run:/run/php/
      - db_run:/run/mysqld/
      - ./arosa/php/7.0/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - httpd_data:/var/www
  php72-fpm:
    build: ./php/7.2
    depends_on:
      - httpd
      - db
    image: "arosa-php:7.2-fpm"
    volumes:
      - php_run:/run/php/
      - db_run:/run/mysqld/
      - ./arosa/php/7.2/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - httpd_data:/var/www
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile-php-apache
    image: arosa-httpd:2.4
    volumes:
      - httpd_config:/etc/apache2
      - httpd_letsencrypt:/etc/letsencrypt
      - httpd_data:/var/www
      - php_run:/run/php/
    ports:
      - "80:80"
      - "443:443"

volumes:
  php_run:
  db_run:
  db_sql_dumps:
    external: true
  db_data:
    external: true
  httpd_config:
    external: true
  httpd_letsencrypt:
    external: true
  httpd_data:
    external: true
