FROM php:apache
RUN apt-get update && \
  apt-get install -y locales && \
  rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
  ln -sf /usr/share/zoneinfo/Europe/Budapest /etc/localtime
ENV LANG=en_US.UTF-8 TZ=Europe/Budapest
RUN a2disconf docker-php && \
  a2dismod php && \
  a2dismod mpm_prefork && \
  a2enmod mpm_event && \
  a2enmod proxy_fcgi && \
  a2enmod ssl && \
  a2enmod rewrite
EXPOSE 443
VOLUME /var/www /var/log/apache2 /etc/apache2
